### PR TITLE
FEATURE: Add activity manager. [WIP]

### PR DESCRIPTION
**Pull request by LennyPhoenix**
Adds support for the activity manager and all its methods, events and data models.

# Progress

- [x] Data Types
  - [x] Activity
    - [x] ActivityTimestamps
    - [x] ActivityAssets
    - [x] ActivityParty (Running into a few problems: [~~#45645~~](https://github.com/godotengine/godot/issues/45645), [#45675](https://github.com/godotengine/godot/issues/45675))
      - [x] PartySize
    - [x] ActivitySecrets
- [x] Methods
  - [x] register_command
  - [x] register_steam
  - [x] update_activity
  - [x] clear_activity
  - [x] send_request_reply
  - [x] send_invite
  - [x] accept_invite
- [x] Events
  - [x] activity_join
  - [x] activity_spectate
  - [x] activity_join_request
  - [x] activity_invite

### CODE REVIEW

**Comment by JezSonic** [comment]
I have a question. You're doing amazing job, how can I help you? (My and my friend's game is using this pulgin also)
I see you have a lot of work to do on this, so i think we can try to help you

**Comment by LennyPhoenix** [comment]
Hey, as of right now I'm trying to figure out the most efficient method for the nested objects to work (this can be seen in data classes like the `ActivityParty `and `Activity`), I'm yet to write any contributing guidelines, but the next thing I'm going to work on after this PR is the relationships manager, which you could start work on now if you want to. Once I have the nested objects working this PR should be done pretty quickly as there isn't much to add after that, the biggest issue right now is having the right type hints for `Resource` properties, as errors like this are appearing allot:

image
(If you have any ideas for this, please let me know :P)

[Here is the project board for things I want to get done for the 1.0 release. I'm probably going to do a pre-release once Activities has been finished.](https://github.com/LennyPhoenix/GodotDiscordSDK/projects/1)

**Comment by LennyPhoenix** [comment]
Remember we also have a [discussions page](https://github.com/LennyPhoenix/GodotDiscordSDK/discussions) for if you want to ask about adding features or making changes :)

**Comment by JezSonic** [comment]
Ok, i didnt see discussions page, i have forked repo, ill try to implement things i need like register command etc also i can help you with parties if you need more people than one to test it

**Comment by LennyPhoenix** [comment]
I also need to implement the [log hook system](https://discord.com/developers/docs/game-sdk/discord#setloghook) at some point, which I can probably get around to later today, as this is something I forgot to do when I first wrote the Core.

**Comment by LennyPhoenix** [comment]
As for contributing to this: feel free to open a PR targeted to the activities branch 👍

**Comment by JezSonic** [comment]
Okie :D

**Comment by LennyPhoenix** [comment]
> I also need to implement the [log hook system](https://discord.com/developers/docs/game-sdk/discord#setloghook) at some point, which I can probably get around to later today, as this is something I forgot to do when I first wrote the Core.

Regarding this, just finished the implementation so it should be on main now.

**Comment by JezSonic** [comment]
For now I'm trying to implement register_command() function. reguster_steam() will be next

**Comment by LennyPhoenix** [comment]
I am having some issues with `update_activity` and `clear_activity`, so I'm going to do some testing to try and get them to work.

**Pull request merged**
